PACKAGE_NAME="rk3588-camera"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="imx708"
BUILT_MODULE_LOCATION[0]="imx708"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
CLEAN[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
